#!/usr/bin/python

print("Content-type: text/html\n\n")

import os, cgi, hashlib

# Creating fieldStorage, which stores the values from the post message
form = cgi.FieldStorage()

username = form.getvalue("username_field")
username_length = len(username)
password = hashlib.md5(form.getvalue("password_field"))
password_length = len(password)
total_length = username_length + password_length

# Find username and password in text document to compare entered data into
try:
    f = open("/home/ec2-user/stitch/users.txt")
    username_start = f.find(username)
    username_end = username + total_length
    print(username + "," + password)
    print(f[username_start:username_end])
    if((username + "," + password) == (f[username_start:username_end])):
        # If the entered username and password an entry, the homepage is generated by the python (print html on the screen)
        print ('<!DOCTYPE html>')
        print ('<html lang="en" dir="ltr">')
        print ('<head><meta charset="uft-8"><title>' + username + ' Stitch Homepage</title><script src="JS/stitch.js"></script><link rel="stylesheet" type="text/css" href="CSS/stitch.css"></head>')
        print ('<body><div id="banner"><div id="banner-content">Welcome to Stitch ' + username + '       <a href="">User Settings</a><a href="">Log off</a></div></div>')
        print ('<p>Test Test</p>')
except IOError:
    # In case of invalid login, refresh the page (clear fields)
    print ("Location: index.html")
finally:
    f.close()